---
title: "Analysis"
author: "Tina Lasisi"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  workflowr::wflow_html:
    toc: yes
    number_sections: yes
editor_options:
  chunk_output_type: console
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(tidyverse)
library(knitr)
library(fs)
library(gridExtra)
library(patchwork)
library(broom.mixed)
library(huxtable)
library(jtools)
library(readxl)
library(dplyr)

F = rprojroot::is_rstudio_project$make_fix_file()
# knitting to pdf
# rmarkdown::render(input = "analysis/analysis.Rmd", output_format = "pdf_document", output_dir = "output")
F = rprojroot::is_rstudio_project$make_fix_file()
palettedf <- tibble(paletteer::palettes_d_names)
# filter(.data = palettedf, length > 10 & type == "qualitative")
knitr::opts_chunk$set(echo = FALSE, include = TRUE, eval = TRUE, warning = FALSE, message = FALSE, fig.retina = 2, fig.width = 8, fig.height = 6)

knitr::opts_knit$set(root.dir = "..")
```

```{r df, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}

df <- read_excel(F("data/current/March2022Sheet.xlsx"), sheet = 1)



df <- df[-c(1,2,3,4,5,30,31,32),][-c(3)][c(1:60),]


# Takes first 15 columns
df1 <- df[,1:9]
colnames(df1) <- c("wind", "wig", "wet_dry", "heatloss", "skin_temp", "resistance", "clo", "amb_temp", "amb_rh")

df1$radiation='on'

# Takes rest of columns
df2 <- df[,10:17]


df2$wet_dry <- c(rep("wet", 24), rep("dry", 36))


colnames(df2) <- c("wind", "wig", "heatloss", "skin_temp", "resistance", "clo", "amb_temp", "amb_rh", "wet_dry")
df2$radiation='off'


df3 <- bind_rows(df1, df2)

df3 <- df3 %>%
  group_by(wind, wig, wet_dry, radiation) %>%
  mutate(trial = row_number()) %>%
  ungroup()

write.csv(df3,F("data/current/Aug2022.csv"), row.names = FALSE)

```
